export const siteConfig = {
  name: "Febe Chukwuma",
  title: "Full Stack Software Engineer",
  description: "Portfolio website of Febe Chukwuma",
  accentColor: "#1d4ed8",
  social: {
    email: "febchuk@gmail.com",
    linkedin: "https://linkedin.com/in/febe-chukwuma",
    twitter: "https://x.com/febchuk",
    github: "https://github.com/febchuk",
  },
  aboutMe:
    "Full Stack Software Engineer with expertise in building cross-platform applications and ML-powered systems. Currently at Salesforce, with experience at Apple (FEA Team), Meta (AR Platform), and Boeing developing production-grade solutions using React, React Native, Python, and modern cloud technologies. Holds an MS in Computer Science (AI specialization) from Georgia Tech and BS in Aerospace Engineering from Virginia Tech. Passionate about creating scalable systems that bridge machine learning with real-world engineering applications.",
  skills: [
    "Python",
    "TypeScript",
    "JavaScript",
    "React",
    "React Native",
    "Svelte",
    "Django",
    "FastAPI",
    "Node.js",
    "Go",
    "GraphQL",
    "REST APIs",
    "Swift",
    "Flutter",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "AWS",
    "Docker",
    "Kubernetes",
    "TensorFlow",
    "PyTorch",
    "WebGL",
    "Three.js",
    "Tailwind CSS",
  ],
  projects: [
    {
      name: "knot allergy",
      description:
        "Social companion app for indie crafters using Flutter for cross-platform mobile development. Grew the user base to 400 monthly active users across iOS & Android within the first four months of launch.",
      link: "https://github.com/febchuk",
      skills: ["Dart", "Flutter", "PostgreSQL", "TravisCI"],
    },
  ],
  experience: [
    {
      company: "Salesforce",
      title: "Full Stack Software Engineer",
      dateRange: "Present",
      bullets: [
        "Building enterprise-scale cloud solutions",
        "Developing customer-facing applications with modern web technologies",
        "Collaborating with cross-functional teams on product innovation",
      ],
    },
    {
      company: "Yahoo",
      title: "Software Engineer",
      dateRange: "2025",
      bullets: [
        "Developed scalable web applications",
        "Implemented modern frontend and backend solutions",
        "Contributed to core platform features",
      ],
    },
    {
      company: "Apple",
      title: "Full Stack Software Engineer - FEA Team",
      dateRange: "2024",
      bullets: [
        "Developed a python-based machine learning web-application that predicts structural failures in product prototypes using FEA (Finite Element Analysis) data, reducing physical testing cycles by 35%",
        "Built custom data processing pipelines that automatically extract, transform, and structure complex simulation results from proprietary CAD/CAE file formats",
        "Created a FastAPI/React application for engineering teams to visualize and analyze failure patterns across multiple simulation scenarios, improving prototype iteration speed",
        "Collaborated with materials engineering and product design teams to integrate predictive insights into the development workflow, enabling data-driven design decisions",
      ],
    },
    {
      company: "Meta",
      title: "Full Stack Software Engineer",
      dateRange: "2023",
      bullets: [
        "Engineered cross-platform React Native applications for Meta's AR platform by implementing GraphQL APIs and optimizing query caching, resulting in 99.9% uptime and sub-100ms response times",
        "Spearheaded development of a TypeScript component library by implementing GraphQL code generation and advanced caching strategies, reducing bundle size by 45% across mobile and AR interfaces",
        "Designed real-time AI integration architecture by building custom React hooks and GraphQL subscriptions, achieving P95 latency under 200ms for LLM-powered features",
      ],
    },
    {
      company: "Boeing",
      title: "Software Engineer / Data Engineer",
      dateRange: "2022",
      bullets: [
        "Developed a full-stack stress analysis platform using Python/Django backend and React frontend, processing complex 3D models in real-time with WebGL",
        "Created RESTful APIs with Django REST framework, implementing rate limiting, caching, and authentication to handle 10K+ daily requests",
        "Built and maintained a TypeScript-based component library used across 5 internal applications",
        "Developed a real-time analytics dashboard using Python, Dash, and WebSocket connections, serving 200+ concurrent users with <100ms response time",
        "Created a centralized data warehouse architecture, implementing efficient ETL processes that reduced data processing time by 60%",
      ],
    },
  ],
  education: [
    {
      school: "Georgia Tech",
      degree: "Master's of Science in Computer Science, Artificial Intelligence",
      dateRange: "Atlanta, GA",
      achievements: [
        "Specialized in Machine Learning and AI",
        "Advanced coursework in Deep Learning, Computer Vision, and Natural Language Processing",
        "Applied ML techniques to real-world engineering problems",
      ],
    },
    {
      school: "Virginia Tech",
      degree: "Bachelor's of Science in Aerospace Engineering, with a Minor in Applied Mathematics",
      dateRange: "Blacksburg, VA",
      achievements: [
        "Combined engineering fundamentals with mathematical rigor",
        "Developed strong foundation in computational methods and numerical analysis",
        "Applied mathematical modeling to complex aerospace systems",
      ],
    },
  ],
};
